### ISSUE TITLE
api-tutorial: clarify if /corpus?include=metrics should use "plays" or "text"

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-notebooks#11]
@cmil there are two ways to get the text count when adding ?metrics to the /corpora endpoint, key plays and text; is there any difference; which should be used?

```
{
    "description": "Edited by Boris Orekhov. Contains a growing number of plays in the Bashkir language. Works still under copyright published with the permission of the rights holders.",
    "uri": "https://dracor.org/api/corpora/bash",
    "title": "Bashkir Drama Corpus",
    "name": "bash",
    "acronym": "BashDraCor",
    "metrics": {
      "plays": 3,
      "characters": 56,
      "male": 37,
      "female": 16,
      "text": 3,
      "sp": 1405,
      "stage": 575,
      "wordcount": {
        "text": 23464,
        "sp": 21184,
        "stage": 3275
      },
      "updated": "2022-07-02T21:04:40.597+02:00"
    },
    "repository": "https://github.com/dracor-org/bashdracor"
  }
```

The line `num_of_plays = corpus['metrics']['text']` uses the field with the key "text"; in the textplus-intro-notebook, I changed this to "plays", but don't know which is the better solution

**Comment by cmil** [comment]
The `plays` property counts the number of `tei:TEI` elements  while `text` counts the `tei:text` elements in the corpus (see https://github.com/dracor-org/dracor-api/blob/638eba48ed4c70892416ff1cdf9ee06125b273ed/modules/api.xqm#L191 and https://github.com/dracor-org/dracor-api/blob/638eba48ed4c70892416ff1cdf9ee06125b273ed/modules/api.xqm#L196).

Normally both numbers should be equal. I don't exactly remember why we introduced `text` as a separate metric. Perhaps as a way to spot inconsistencies in a corpus.

**Comment by lehkost** [comment]
Oh, interesting one! I might have an explanation, even if I can't recall that we ever discussed the implementation of both, ```plays``` and ```text```. So, in the very beginning, around 2015 or so, we inherited 13 "plays" from the TextGrid Repository that where wrapped in ```<teiCorpus>```, thus containing several ```<text>``` elements, see this blogpost from back then, written by @mathias-goebel and yours truly: ["A (Not So) Simple Question and a Somewhat Diabolic Answer"](https://dlina.github.io/A-Not-So-Simple-Question/).

When we converted TextGrid plays to start GerDraCor, we absolutely abandoned ```<teiCorpus>``` and dissolved contained plays into single files. So, ```text``` might be obsolete here (but I might be wrong)."

**Comment by lehkost** [comment]
Oh, I found another reason that might have triggered the usage of both, have a look at the Swedish corpus, where we have "plays: 68" and "text: 73". I remember we discussed this some years ago but never had the time to get back to SweDraCor. So, it actually might make sense to keep both.

**Comment by hsluytergaethje** [comment]
Ok, if I get that right, the number of plays that are accessible in DraCor corresponds to the numbers of `plays` not `text`. At least this is the case for SweDraCor. I would therefore use `plays` in the notebook when listing the corpora.
